### ISSUE TITLE
YAML conf file

### ISSUE THREAD

**Issue by dnlo** [devopsfaith/api2html#27]
Reads better than JSON

```
robots: true
sitemap: true
static_txt_content:
  - hello.txt
templates:
  home: home.mustache
  post: post.mustache
layouts:
  main: main_layout.mustache
extra:
  lang: en-US
  copyright: © 2018 My Company
public_folder:
  path_to_folder: ./public
  url_prefix: /
pages:
  - name: post
    URLPattern: '/posts/:post'
    BackendURLPattern: 'https://jsonplaceholder.typicode.com/posts/:post'
    Template: post
    Layout: main
    CacheTTL: 3600s
  - name: home
    URLPattern: /
    BackendURLPattern: 'https://jsonplaceholder.typicode.com/posts'
    Template: home
    Layout: main
    CacheTTL: 3600s
    IsArray: true
    extra:
      is_home: 
```
